name: "Push to Cachix"

on:
  workflow_call:
    inputs:
      cachix_name:
        description: "Name of the Cachix cache"
        required: true
        type: string
    secrets:
      CACHIX_SIGNING_KEY:
        required: true
      REPO_TOKEN:
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: ${{ inputs.cachix_name }}
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - run: nix build --no-link --print-out-paths > /tmp/paths
      - run: cat /tmp/paths | cachix push ${{ inputs.cachix_name }}

      - name: Trigger mox-flake update
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/mox-desktop/mox-flake/dispatches \
            -d '{"event_type":"dependency-updated"}'
